### ISSUE TITLE
Won't store any reforged relic gear

### ISSUE THREAD

**Issue by GetAwayCoxn** [ThornyFFXI/Porter#3]
After the nil error fix from the commit the other day now porter wont store any relic reforged gear. I verified for 109 and 119 +1/2/3. /lac prepack and /lac pack both do nothing as if it is not recognizing that these pieces should be stored.
EDIT: unpacking seems to be working fine

**Comment by ThornyFFXI** [comment]
Pushed a fix.  I blocked augmented items in general with the earlier adjustment, intending to fix a related problem(ruaun god gear and abjuration gear being augmented), but in the process it made relic unstorable.  I extended the augment check from relic+2 to apply to reforged, which should always be augmented, and that should fix it.

**Comment by GetAwayCoxn** [comment]
Updated data.lua from your latest commit and this is still a no go. Only quickly tested for a +3 relic item and not one from each of the array you added but porter still doesn't recognize that it should be stored, prepack spits out '0 items were retrieved. 0 items remain' and pack just says Packing complete of course.

**Comment by ThornyFFXI** [comment]
Finally gave in and grabbed some armor to verify personally, and this seems completely resolved in 1.06.  For my own sanity, it'd be appreciated if you could also confirm the issue is resolved when you are able.

**Comment by GetAwayCoxn** [comment]
Tested with 2 chars, several pieces each, seems to be working great now. Thank you for your time on this.
